console.log("Hi i am console screen");
var lion="Roshan";
var wolf="helal ajeesdeen";
console.log("first name",lion);
console.log("last name",wolf);
var cat=lion.concat(wolf);
console.log("full name",cat);
var dog=cat.length;
console.log("length",dog);
var b="I like code class";
console.log(b);
var R=b.replace("like","love");
console.log(R);
var f="Olympus Academy";
var n=f.toLowerCase();
console.log(n);
var f1="Olympus Academy";
var n1=f1.toUpperCase();
console.log(n1);
var a=Math.sqrt(16);
console.log(a);
var l=Math.max(500,1000);
console.log(l);
var l1=Math.min(500,1000);
console.log(l1);
var z=Math.pow(2,4);
console.log(z);